### ISSUE TITLE
PHP Fatal error: Uncaught Error: Cannot use object of type WPGlobus as array

### ISSUE THREAD

**Issue by AiratHalitov** [WPGlobus/WPGlobus#72]
Error log:
```
[Thu Dec 27 18:58:22.878386 2018] [php7:error] [pid 4545] [client IP:PORT] PHP Fatal error:  Uncaught Error: Cannot use object of type WPGlobus as array in /site_path/wp-content/plugins/wpglobus/includes/builders/class-wpglobus-config-builder.php:289
Stack trace:
#0 /site_path/wp-content/plugins/wpglobus/includes/builders/class-wpglobus-config-builder.php(491): WPGlobus_Config_Builder->get_language()
#1 /site_path/wp-content/plugins/wpglobus/includes/class-wpglobus.php(2415): WPGlobus_Config_Builder->get_data()
#2 /site_path/wp-includes/class-wp-hook.php(286): WPGlobus->enqueue_wpglobus_js('')
#3 /site_path/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#4 /site_path/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#5 /site_path/wp-includes/script-loader.php(2231): do_action('wp_enqueue_scri...')
#6 /site_path/wp-includes/class-wp-hook.php(286): wp_enqueue_s in /site_path/wp-content/plugins/wpglobus/includes/builders/class-wpglobus-config-builder.php on line 289
```
I have seen this error in the logs several times.

**Configuration:**
– WPGlobus 2.1.2
– WordPress 5.0.2
– PHP 7.2.13-1+ubuntu16.04.1+deb.sury.org+1

**Additional Info:**
– Classic Editor 1.3
– Elementor 2.3.8

https://wordpress.org/support/topic/php-fatal-error-uncaught-error-cannot-use-object-of-type-wpglobus-as-array/

**Comment by AiratHalitov** [comment]
В последнее время я не вижу этой ошибки. Правда я перестал использовать Classic Editor и Elementor, а перешел на Gutenberg. Может эта ошибка уже неактуальна. Я не знаю. 

WPGlobus 2.1.10
WordPress 5.1.0
Gutenberg 5.1.1

**Comment by AiratHalitov** [comment]
The bug is still actual

Error log:
```
2019-03-27T06:20:07+00:00 CRITICAL Uncaught Error: Cannot use object of type WPGlobus as array in /site_path/wp-content/plugins/wpglobus/includes/builders/class-wpglobus-config-builder.php:292
Stack trace:
#0 /site_path/wp-content/plugins/wpglobus/includes/builders/class-wpglobus-config-builder.php(494): WPGlobus_Config_Builder->get_language()
#1 /site_path/wp-content/plugins/wpglobus/includes/class-wpglobus.php(2429): WPGlobus_Config_Builder->get_data()
#2 /site_path/wp-includes/class-wp-hook.php(286): WPGlobus->enqueue_wpglobus_js('')
#3 /site_path/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#4 /site_path/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#5 /site_path/wp-includes/script-loader.php(2463): do_action('wp_enqueue_scri...')
#6 /site_path/wp-includes/class-wp-hook.php(286): wp_enqueue_s в /site_path/wp-content/plugins/wpglobus/includes/builders/class-wpglobus-config-builder.php на строке 292
```
**Configuration:**

- WPGlobus 2.1.11
- Gutenberg 5.3.0
- WordPress 5.1.1
- PHP 7.2.16-1+ubuntu16.04.1+deb.sury.org+1

**Comment by jasalt** [comment]
I got this after updating a site from WP 4.9 to 5.1.1 and I think I managed to fix it in this case by changing lines in `includes/builders/class-wpglobus-config-builder.php` with `$GLOBALS['WPGlobus']['post_type']` and `$GLOBALS['WPGlobus']['post_id']` to have `$GLOBALS['WPGlobus']->post_type` and `$GLOBALS['WPGlobus']->post_id` instead.

Here's full diff against latest version 2.1.12 from WP plugin directory.

```
diff --git a/includes/builders/class-wpglobus-config-builder.php b/includes/builders/class-wpglobus-config-builder.php
index ddb8dda..e0964ac 100644
--- a/includes/builders/class-wpglobus-config-builder.php
+++ b/includes/builders/class-wpglobus-config-builder.php
@@ -290,7 +290,7 @@ if ( ! class_exists( 'WPGlobus_Config_Builder' ) ) :
                                         */
                                        $_continue = false;

-                                       if ( isset( $GLOBALS['WPGlobus'] ) && ! empty( $GLOBALS['WPGlobus']['post_type'] ) ) {
+                                       if ( isset( $GLOBALS['WPGlobus'] ) && ! empty( $GLOBALS['WPGlobus']->post_type ) ) {
                                                $_continue = true;
                                        }

@@ -302,8 +302,8 @@ if ( ! class_exists( 'WPGlobus_Config_Builder' ) ) :
                                                 *
                                                 * @see \WPGlobus_Builders::is_gutenberg()
                                                 */
-                                               if ( isset( $GLOBALS['WPGlobus'] ) && ! empty( $GLOBALS['WPGlobus']['post_id'] ) ) {
-                                                       $post_id = $GLOBALS['WPGlobus']['post_id'];
+                                               if ( isset( $GLOBALS['WPGlobus'] ) && ! empty( $GLOBALS['WPGlobus']->post_id ) ) {
+                                                       $post_id = $GLOBALS['WPGlobus']->post_id;
                                                } else {
                                                        $_request_uri = explode( '/', $_SERVER['REQUEST_URI'] );
```

Versions:

- Wordpress 5.1.1
- 7.2.16-1+ubuntu16.04.1+deb.sury.org+1

**Comment by AiratHalitov** [comment]
@jasalt 
You can fork this repository, create a new branch and push your PR with this patch.
